# Generated by Django 5.0 on 2023-12-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatentDatabase',
            fields=[
                ('Application_Number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Application Number')),
                ('Application_Type', models.TextField(null=True, verbose_name='Application Type')),
                ('Date_of_Publication', models.TextField(null=True, verbose_name='Date of Publication')),
                ('Title_of_Invention', models.TextField(null=True, verbose_name='Title of Invention')),
                ('Field_of_Invention', models.TextField(null=True, verbose_name='Field of Invention')),
                ('E_Mail', models.TextField(null=True, verbose_name='E-Mail')),
                ('Alternate_E_Mail', models.TextField(null=True, verbose_name='Alternate E-Mail')),
                ('Request_Examination_Date', models.TextField(null=True, verbose_name='Request Examination Date')),
            ],
            options={
                'verbose_name_plural': 'Patent Database',
                'db_table': 'public.patent_database',
            },
        ),
    ]
